### ISSUE TITLE
주문 관련 버그픽스

### ISSUE THREAD

**Issue by SuranS2** [SuranS2/ShouxKream#45]
- ../checkout/complete 에서 ../me/checkouts 페이지로 갈때 오류 발생
complete:35  GET https://jrqggzccfxaqcbkg.tunnel-pt.elice.io/elice-rabbit.png 401 (Unauthorized) : 
{
"errorMessage": "??? ?????."
}
- /cart/summary 에서 상품없어도 /checkout 페이지로 바로 넘어가짐
ReferenceError: address is not defined
at insertUserData (checkout.js:178:3)
Uncaught (in promise) Error
at Module.get (api.js:19:11)
at async insertCheckOutSummary (checkout.js:113:23)

**Comment by SuranS2** [comment]
changed due date to October 24, 2024

**Comment by SuranS2** [comment]
mentioned in commit 2325e337a7e9ac5703018ba38142f8cb82f124c7
